### ISSUE TITLE
Context not available inside Vue component

### ISSUE THREAD

**Issue by kenjura** [chrisvfritz/vue-2.0-simple-routing-example#10]
To really get the most out of Page.js, it seems like we'd need the context within the Vue component itself. What's a good way to do this? 

My best attempt so far is:
(src/main.js)
line 10: render (h) { return h(this.ViewComponent, { props: { context:this.context} }) }
line 15: page(route, (ctx) => { app.context = ctx; app.ViewComponent = Component })

(src/pages/Home.vue)
add before line 11: props: [ 'context' ]
(repeat for each page)

Not sure if this is a good practice or not, but it seems to work.

**Comment by chrisvfritz** [comment]
To really get the most out of routing in general, I'd just recommend using Vue Router, as it's built to solve the problem of tight integration with Vue. 🙂  This project is only made to demonstrate how routing essentially works, reveal some of the apparent magic, and demonstrating that for very simple projects, learning to use Vue Router may not even be necessary.
