### ISSUE TITLE
Q: Scroll position & keep alive

### ISSUE THREAD

**Issue by adyz** [chrisvfritz/vue-2.0-simple-routing-example#13]
Hey, thank you for this bare-bones setup.

I was wondering if you've ever thought about Scroll position & keep alive.

I cloned this repo and added more content to each page and I've make the header fixed with CSS. 

It looks like when I click on a link the new page loads, but the scroll is maintained, but the default behavior should be to load the new page with scroll position at zero.

I will do more research in the weekend for this, but I would like to know if you already have any insights about scroll position and keep-alive without the vuerouter and if you are willing to share with us.

Thank you, 
Adrian

**Comment by chrisvfritz** [comment]
Where things begin to get more complicated, I'll always just switch to Vue Router. 🙂 I recommend checking out the source if you'd like to see how the router solves these problems - you may be surprised by the number of edge cases that have to be considered!
