### ISSUE TITLE
there are some problems when I  execute 'npm run build'

### ISSUE THREAD

**Issue by Pasoul** [chrisvfritz/vue-2.0-simple-routing-example#14]
when i  execute 'npm run build', and start a server in root directory，the page is ok, but when i refresh the browser, the page is wrong with Cannot GET /about

**Comment by chrisvfritz** [comment]
That would be an issue with the server you're using. For servers configured for single-page applications, all requests will be redirected to the root. If you try it on surge or with servers such as `pushstate-server`, it will work.
