### ISSUE TITLE
When I run "npm install" I got this

### ISSUE THREAD

**Issue by ghost** [chrisvfritz/vue-2.0-simple-routing-example#15]
`npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for updates, join slack.babeljs.io for discussion and help support at opencollective.com/babel`

**Comment by ghost** [comment]
Hi @binguanghe,

It is nothing to worry about. Read more about it [here](https://babeljs.io/env).
Project works fine, with `babel-preset-es2015` or `babel-preset-env`.

**Comment by chrisvfritz** [comment]
PR welcome to migrate to `babel-present-env` if anyone wants to take the time. 🙂

**Comment by ghost** [comment]
@chrisvfritz 
Pull request created here: [#16](https://github.com/chrisvfritz/vue-2.0-simple-routing-example/pull/16).
