### ISSUE TITLE
Request: history update

### ISSUE THREAD

**Issue by violacase** [chrisvfritz/vue-2.0-simple-routing-example#4]
Hi, nice work. One issue:
Watching browser history in Chrome all entries are pointing to the home url.  This isn't a reflection of the reality. What can I (or you?) do to make that right?

**Comment by chrisvfritz** [comment]
I'm not sure I can replicate this - or perhaps just don't understand what you mean. When visiting [the demo](http://vue-2-simple-routing-example.surge.sh/), clicking around to different pages then using the browser's back button works correctly.

**Comment by chrisvfritz** [comment]
There hasn't been any traction on this for a while, so closing for now. I'm happy to reopen pending new information or a reproduction.
