### ISSUE TITLE
Question: how serve a build

### ISSUE THREAD

**Issue by violacase** [chrisvfritz/vue-2.0-simple-routing-example#5]
After `npm run build` this is what's in the dist folder:
```
-a----       20-12-2016     13:24          58065 build.js
-a----       20-12-2016     13:24         475164 build.js.map
```
How do  I serve this?

**Comment by chrisvfritz** [comment]
From the index.html file in the root.

**Comment by chrisvfritz** [comment]
@violacase Closing for now, unless you report that this did not resolve your issue.
